version: 0.0
os: linux

files:
  - source: /
    destination: /home/dev-table/ # 인스턴스에서 파일이 저장될 위치
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user